export const listPlayers = [
    // {
    //     type: 'Angel',
    //     name: 'jesus',
    //     x: 40,
    //     y: 0,
    //     width: 1.2,
    //     height: 5,
    //     sprite: 'A',
    //     deployX: 80,
    //     deployY: 80,
    // },
    {
        type: 'Archangel',
        name: 'miguel',
        x: 45,
        y: 0,
        width: 1.2,
        height: 5,
        sprite: 'B',
        direction: 'RIGHT',
        deployX: 20,
        deployY: 20,
    },
    {
        type: 'Archangel',
        name: 'Jesus',
        x: 40,
        y: 0,
        width: 1.2,
        height: 5,
        sprite: 'A',
        direction: 'RIGHT',
        deployX: 80,
        deployY: 80,
    },
]